package ru.geekbrains.entities.objects;

public enum ObjectType {

    OBJECT,
    DRIVEN_OBJECT,
    PROJECTILE,
    SHELL,
    BLACKHOLE_SHELL,
    FLAK_SHELL,
    PLASMA_FLAK_SHELL,
    EXPLOSION_FLAK_SHELL,
    FRAG,
    PLASMA_FRAG,
    EMP_FRAG,
    EXPLOSION_FRAG,
    BULLET,
    SHIP,
    MISSILE,       // base type
    BASIC_MISSILE, // base type for medium size missiles
    HE_MISSILE,
    FAST_MISSILE,
    EMP_MISSILE,
    GRAVITY_REPULSE_MISSILE,
    ANTIMISSILE,
    PLASMA_FRAG_MISSILE,
    FORCE_SHIELD,
    ENEMY_SHIP,
    MAIN_ENEMY_SHIP,
    BATTLE_ENEMY_SHIP,
    MISSILE_ENEMY_SHIP,
    PLAYER_SHIP,
    PLANET,
    MISSILE_LAUNCHER,
    MINIGUN,
    PLAYER_KERMAN

}
